---
name: Module-Build-JSAN
version: 0.04
author: []
abstract: Build JavaScript distributions for JSAN
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::Build: 0.2701
  Pod::Select: 1.3
  Pod::Simple: 3.02
  Pod::Simple::HTML: 3.01
  Pod::Simple::Text: 2.02
  Pod::Stripper: 0.22
provides:
  Module::Build::JSAN:
    file: lib/Module/Build/JSAN.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
